name: Packages for Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Ubuntu packages
      run: |
        sudo apt install build-essential cmake debhelper-compat
        dpkg-buildpackage -uc -us
        mkdir out-debs
        'cp ../{*.deb,*.changes,*.buildinfo,*.tar.gz,*.dsc} out-debs/'

    - name: Upload artifacts
      uses: actions/upload-artifact@v5.0.0
      with:
        name: dist-without-markdown
        path: out-debs/*
