name: Packages for Ubuntu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Ubuntu packages
      run: |
        sudo apt install build-essential cmake debhelper-compat
        dpkg-buildpackage --no-sign
        mkdir out-debs
        cp ../*.deb out-debs/
        cp ../*.ddeb out-debs/
        cp ../*.changes out-debs/
        cp ../*.buildinfo out-debs/
        cp ../*.tar.xz out-debs/
        cp ../*.dsc out-debs/

    - name: Upload artifacts
      uses: actions/upload-artifact@v5.0.0
      with:
        name: debs
        path: out-debs/*
